services:
  frontend-service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: edutrack-frontend
    ports:
      - "3000:80"
    environment:
      - VITE_API_URL=http://localhost:8085/api/v1
